apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /{{ .Values.appName }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-front-svc
                port:
                  number: 80
{{/*          - path: /event-server*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ .Values.appName }}-back-svc*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}