apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-front-svc
  labels:
    app: {{ .Values.appName }}-front-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: {{ .Values.appName }}-front
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.appName }}-back-svc*/}}
{{/*  labels:*/}}
{{/*    app: {{ .Values.appName }}-back-svc*/}}
{{/*  annotations:*/}}
{{/*    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"*/}}
{{/*    traefik.ingress.kubernetes.io/service.sticky.cookie.name: cookie*/}}
{{/*    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"*/}}
{{/*spec:*/}}
{{/*  type: ClusterIP*/}}
{{/*  ports:*/}}
{{/*    - port: 80*/}}
{{/*      targetPort: {{ .Values.backend.containerPort }}*/}}
{{/*  selector:*/}}
{{/*    app: {{ .Values.appName }}-back*/}}
